import { Achievement, Title } from '@/types/achievements';

export const ACHIEVEMENTS: Achievement[] = [
  // Combat Achievements
  {
    id: 'ach_novice_fighter',
    name: 'Novice Fighter',
    description: 'Win 10 battles',
    category: 'combat',
    tier: 'bronze',
    requirement: 10,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_veteran_warrior',
    name: 'Veteran Warrior',
    description: 'Win 50 battles',
    category: 'combat',
    tier: 'silver',
    requirement: 50,
    progress: 0,
    completed: false,
    unlocksTitle: 'veteran',
  },
  {
    id: 'ach_champion',
    name: 'Champion',
    description: 'Win 200 battles',
    category: 'combat',
    tier: 'gold',
    requirement: 200,
    progress: 0,
    completed: false,
    unlocksTitle: 'champion',
  },
  {
    id: 'ach_critical_master',
    name: 'Critical Master',
    description: 'Land 50 critical hits',
    category: 'combat',
    tier: 'silver',
    requirement: 50,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_untouchable',
    name: 'Untouchable',
    description: 'Evade 100 attacks',
    category: 'mastery',
    tier: 'silver',
    requirement: 100,
    progress: 0,
    completed: false,
    unlocksTitle: 'untouchable',
  },
  
  // Progression Achievements
  {
    id: 'ach_rising_star',
    name: 'Rising Star',
    description: 'Reach level 5',
    category: 'progression',
    tier: 'bronze',
    requirement: 5,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_hero',
    name: 'Hero',
    description: 'Reach level 15',
    category: 'progression',
    tier: 'silver',
    requirement: 15,
    progress: 0,
    completed: false,
    unlocksTitle: 'hero',
  },
  {
    id: 'ach_legend',
    name: 'Legend',
    description: 'Reach level 30',
    category: 'progression',
    tier: 'gold',
    requirement: 30,
    progress: 0,
    completed: false,
    unlocksTitle: 'legend',
  },
  
  // Collection Achievements
  {
    id: 'ach_treasure_hunter',
    name: 'Treasure Hunter',
    description: 'Find 10 items',
    category: 'collection',
    tier: 'bronze',
    requirement: 10,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_legendary_collector',
    name: 'Legendary Collector',
    description: 'Own 5 legendary items',
    category: 'collection',
    tier: 'platinum',
    requirement: 5,
    progress: 0,
    completed: false,
    unlocksTitle: 'collector',
  },
  
  // Mastery Achievements
  {
    id: 'ach_glass_cannon',
    name: 'Glass Cannon',
    description: 'Win a battle with less than 10% health',
    category: 'mastery',
    tier: 'gold',
    requirement: 1,
    progress: 0,
    completed: false,
    unlocksTitle: 'fearless',
  },
  {
    id: 'ach_wealthy',
    name: 'Wealthy Warrior',
    description: 'Earn 10,000 total gold',
    category: 'progression',
    tier: 'silver',
    requirement: 10000,
    progress: 0,
    completed: false,
  },

  // Dungeon Achievements
  {
    id: 'ach_dungeon_novice',
    name: 'Dungeon Crawler',
    description: 'Complete your first dungeon',
    category: 'dungeon',
    tier: 'bronze',
    requirement: 1,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_dungeon_veteran',
    name: 'Dungeon Veteran',
    description: 'Complete 10 dungeons',
    category: 'dungeon',
    tier: 'silver',
    requirement: 10,
    progress: 0,
    completed: false,
    unlocksTitle: 'dungeon_master',
  },
  {
    id: 'ach_dungeon_master',
    name: 'Dungeon Master',
    description: 'Complete 50 dungeons',
    category: 'dungeon',
    tier: 'gold',
    requirement: 50,
    progress: 0,
    completed: false,
    unlocksTitle: 'delver',
  },
  {
    id: 'ach_floor_clearer',
    name: 'Floor Clearer',
    description: 'Clear 100 dungeon floors',
    category: 'dungeon',
    tier: 'silver',
    requirement: 100,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_endless_depths',
    name: 'Endless Depths',
    description: 'Clear 500 dungeon floors',
    category: 'dungeon',
    tier: 'platinum',
    requirement: 500,
    progress: 0,
    completed: false,
    unlocksTitle: 'abyssal',
  },
  {
    id: 'ach_boss_slayer',
    name: 'Boss Slayer',
    description: 'Defeat 10 dungeon bosses',
    category: 'dungeon',
    tier: 'silver',
    requirement: 10,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_boss_hunter',
    name: 'Boss Hunter',
    description: 'Defeat 50 dungeon bosses',
    category: 'dungeon',
    tier: 'gold',
    requirement: 50,
    progress: 0,
    completed: false,
    unlocksTitle: 'boss_slayer',
  },

  // Trading Achievements
  {
    id: 'ach_first_sale',
    name: 'First Sale',
    description: 'Sell your first item on the marketplace',
    category: 'trading',
    tier: 'bronze',
    requirement: 1,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_merchant_novice',
    name: 'Budding Merchant',
    description: 'Sell 10 items on the marketplace',
    category: 'trading',
    tier: 'silver',
    requirement: 10,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_merchant_master',
    name: 'Master Merchant',
    description: 'Sell 50 items on the marketplace',
    category: 'trading',
    tier: 'gold',
    requirement: 50,
    progress: 0,
    completed: false,
    unlocksTitle: 'merchant_prince',
  },
  {
    id: 'ach_big_spender',
    name: 'Big Spender',
    description: 'Buy 10 items from the marketplace',
    category: 'trading',
    tier: 'silver',
    requirement: 10,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_shopaholic',
    name: 'Shopaholic',
    description: 'Buy 50 items from the marketplace',
    category: 'trading',
    tier: 'gold',
    requirement: 50,
    progress: 0,
    completed: false,
    unlocksTitle: 'collector_supreme',
  },
  {
    id: 'ach_trade_partner',
    name: 'Trade Partner',
    description: 'Complete 5 player trades',
    category: 'trading',
    tier: 'silver',
    requirement: 5,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_trading_mogul',
    name: 'Trading Mogul',
    description: 'Complete 25 player trades',
    category: 'trading',
    tier: 'gold',
    requirement: 25,
    progress: 0,
    completed: false,
    unlocksTitle: 'mogul',
  },
  {
    id: 'ach_gold_rush',
    name: 'Gold Rush',
    description: 'Earn 10,000 gold from marketplace sales',
    category: 'trading',
    tier: 'silver',
    requirement: 10000,
    progress: 0,
    completed: false,
  },
  {
    id: 'ach_tycoon',
    name: 'Tycoon',
    description: 'Earn 100,000 gold from marketplace sales',
    category: 'trading',
    tier: 'platinum',
    requirement: 100000,
    progress: 0,
    completed: false,
    unlocksTitle: 'tycoon',
  },
];

export const TITLES: Record<string, Title> = {
  century_fighter: {
    id: 'century_fighter',
    name: 'Century Fighter',
    color: 'hsl(var(--primary))',
    description: 'Won 100 battles',
  },
  master_warrior: {
    id: 'master_warrior',
    name: 'Master Warrior',
    color: 'hsl(45, 100%, 60%)', // gold
    description: 'Reached level 20',
  },
  collector: {
    id: 'collector',
    name: 'The Collector',
    color: 'hsl(280, 100%, 70%)', // purple
    description: 'Master of legendary items',
  },
  merchant: {
    id: 'merchant',
    name: 'Merchant',
    color: 'hsl(142, 76%, 50%)', // green
    description: 'Accumulated great wealth',
  },
  devastator: {
    id: 'devastator',
    name: 'Devastator',
    color: 'hsl(0, 100%, 60%)', // red
    description: 'Dealt massive damage',
  },
  veteran: {
    id: 'veteran',
    name: 'Veteran',
    color: 'hsl(210, 70%, 60%)', // blue
    description: 'Experienced warrior',
  },
  champion: {
    id: 'champion',
    name: 'Champion',
    color: 'hsl(45, 100%, 50%)', // bright gold
    description: 'Arena champion',
  },
  untouchable: {
    id: 'untouchable',
    name: 'Untouchable',
    color: 'hsl(180, 100%, 60%)', // cyan
    description: 'Master of evasion',
  },
  hero: {
    id: 'hero',
    name: 'Hero',
    color: 'hsl(30, 100%, 60%)', // orange
    description: 'Rising power',
  },
  legend: {
    id: 'legend',
    name: 'Legend',
    color: 'hsl(45, 100%, 70%)', // golden yellow
    description: 'Legendary warrior',
  },
  fearless: {
    id: 'fearless',
    name: 'Fearless',
    color: 'hsl(350, 100%, 60%)',
    description: 'Thrives in danger',
  },
  dungeon_master: {
    id: 'dungeon_master',
    name: 'Dungeon Master',
    color: 'hsl(270, 70%, 50%)',
    description: 'Veteran of the depths',
  },
  delver: {
    id: 'delver',
    name: 'The Delver',
    color: 'hsl(260, 80%, 60%)',
    description: 'Master of dungeons',
  },
  abyssal: {
    id: 'abyssal',
    name: 'Abyssal',
    color: 'hsl(280, 100%, 40%)',
    description: 'One with the darkness',
  },
  boss_slayer: {
    id: 'boss_slayer',
    name: 'Boss Slayer',
    color: 'hsl(0, 80%, 55%)',
    description: 'Destroyer of bosses',
  },
  merchant_prince: {
    id: 'merchant_prince',
    name: 'Merchant Prince',
    color: 'hsl(45, 90%, 55%)',
    description: 'Master of trade',
  },
  collector_supreme: {
    id: 'collector_supreme',
    name: 'Collector Supreme',
    color: 'hsl(200, 80%, 60%)',
    description: 'Buys everything',
  },
  mogul: {
    id: 'mogul',
    name: 'The Mogul',
    color: 'hsl(35, 100%, 50%)',
    description: 'Trading empire builder',
  },
  tycoon: {
    id: 'tycoon',
    name: 'Tycoon',
    color: 'hsl(50, 100%, 45%)',
    description: 'Richest in the realm',
  },
};
