import { SkillTree, SkillTreeNode } from '@/types/skillTree';
import { CharacterClass } from '@/types/game';

const FIGHTER_NODES: SkillTreeNode[] = [
  // Offense Branch (Column 0)
  {
    id: 'fighter_power_strike',
    name: 'Power Strike',
    description: '+10 Attack',
    branch: 'offense',
    cost: 1,
    prerequisite: null,
    effect: { attack: 10 },
    unlocked: false,
    row: 0,
    column: 0,
  },
  {
    id: 'fighter_crushing_blow',
    name: 'Crushing Blow',
    description: '+15 Attack, +5% Crit Chance',
    branch: 'offense',
    cost: 2,
    prerequisite: 'fighter_power_strike',
    effect: { attack: 15, critChance: 5 },
    unlocked: false,
    row: 1,
    column: 0,
  },
  {
    id: 'fighter_berserker',
    name: 'Berserker Rage',
    description: '+25 Attack, +10% Crit Chance',
    branch: 'offense',
    cost: 3,
    prerequisite: 'fighter_crushing_blow',
    effect: { attack: 25, critChance: 10 },
    unlocked: false,
    row: 2,
    column: 0,
  },
  
  // Defense Branch (Column 1)
  {
    id: 'fighter_iron_skin',
    name: 'Iron Skin',
    description: '+10 Defense',
    branch: 'defense',
    cost: 1,
    prerequisite: null,
    effect: { defense: 10 },
    unlocked: false,
    row: 0,
    column: 1,
  },
  {
    id: 'fighter_shield_wall',
    name: 'Shield Wall',
    description: '+15 Defense, +30 Health',
    branch: 'defense',
    cost: 2,
    prerequisite: 'fighter_iron_skin',
    effect: { defense: 15, health: 30 },
    unlocked: false,
    row: 1,
    column: 1,
  },
  {
    id: 'fighter_unbreakable',
    name: 'Unbreakable',
    description: '+25 Defense, +50 Health',
    branch: 'defense',
    cost: 3,
    prerequisite: 'fighter_shield_wall',
    effect: { defense: 25, health: 50 },
    unlocked: false,
    row: 2,
    column: 1,
  },
  
  // Utility Branch (Column 2)
  {
    id: 'fighter_battle_cry',
    name: 'Battle Cry',
    description: '+5 Speed, +5% Evasion',
    branch: 'utility',
    cost: 1,
    prerequisite: null,
    effect: { speed: 5, evasion: 5 },
    unlocked: false,
    row: 0,
    column: 2,
  },
  {
    id: 'fighter_veteran',
    name: 'War Veteran',
    description: '+10 Speed, +10 Luck',
    branch: 'utility',
    cost: 2,
    prerequisite: 'fighter_battle_cry',
    effect: { speed: 10, luck: 10 },
    unlocked: false,
    row: 1,
    column: 2,
  },
  {
    id: 'fighter_second_wind',
    name: 'Second Wind',
    description: '+15 Speed, +20 Health',
    branch: 'utility',
    cost: 3,
    prerequisite: 'fighter_veteran',
    effect: { speed: 15, health: 20 },
    unlocked: false,
    row: 2,
    column: 2,
  },
];

const MAGE_NODES: SkillTreeNode[] = [
  // Elemental Branch
  {
    id: 'mage_fireball',
    name: 'Fireball',
    description: '+12 Attack',
    branch: 'offense',
    cost: 1,
    prerequisite: null,
    effect: { attack: 12 },
    unlocked: false,
    row: 0,
    column: 0,
  },
  {
    id: 'mage_inferno',
    name: 'Inferno',
    description: '+18 Attack, +5% Crit',
    branch: 'offense',
    cost: 2,
    prerequisite: 'mage_fireball',
    effect: { attack: 18, critChance: 5 },
    unlocked: false,
    row: 1,
    column: 0,
  },
  {
    id: 'mage_meteor',
    name: 'Meteor Storm',
    description: '+30 Attack, +12% Crit',
    branch: 'offense',
    cost: 3,
    prerequisite: 'mage_inferno',
    effect: { attack: 30, critChance: 12 },
    unlocked: false,
    row: 2,
    column: 0,
  },
  
  // Arcane Branch
  {
    id: 'mage_mana_shield',
    name: 'Mana Shield',
    description: '+8 Defense, +5% Evasion',
    branch: 'defense',
    cost: 1,
    prerequisite: null,
    effect: { defense: 8, evasion: 5 },
    unlocked: false,
    row: 0,
    column: 1,
  },
  {
    id: 'mage_arcane_mastery',
    name: 'Arcane Mastery',
    description: '+12 Defense, +10 Attack',
    branch: 'defense',
    cost: 2,
    prerequisite: 'mage_mana_shield',
    effect: { defense: 12, attack: 10 },
    unlocked: false,
    row: 1,
    column: 1,
  },
  {
    id: 'mage_time_warp',
    name: 'Time Warp',
    description: '+20 Defense, +15 Speed',
    branch: 'defense',
    cost: 3,
    prerequisite: 'mage_arcane_mastery',
    effect: { defense: 20, speed: 15 },
    unlocked: false,
    row: 2,
    column: 1,
  },
  
  // Summoning Branch
  {
    id: 'mage_familiar',
    name: 'Familiar',
    description: '+15 Luck',
    branch: 'utility',
    cost: 1,
    prerequisite: null,
    effect: { luck: 15 },
    unlocked: false,
    row: 0,
    column: 2,
  },
  {
    id: 'mage_elemental',
    name: 'Elemental',
    description: '+10 Attack, +10 Defense',
    branch: 'utility',
    cost: 2,
    prerequisite: 'mage_familiar',
    effect: { attack: 10, defense: 10 },
    unlocked: false,
    row: 1,
    column: 2,
  },
  {
    id: 'mage_guardian',
    name: 'Ancient Guardian',
    description: '+40 Health, +15 Defense',
    branch: 'utility',
    cost: 3,
    prerequisite: 'mage_elemental',
    effect: { health: 40, defense: 15 },
    unlocked: false,
    row: 2,
    column: 2,
  },
];

const ARCHER_NODES: SkillTreeNode[] = [
  // Precision Branch
  {
    id: 'archer_deadly_aim',
    name: 'Deadly Aim',
    description: '+10 Attack, +5% Crit',
    branch: 'offense',
    cost: 1,
    prerequisite: null,
    effect: { attack: 10, critChance: 5 },
    unlocked: false,
    row: 0,
    column: 0,
  },
  {
    id: 'archer_headshot',
    name: 'Headshot',
    description: '+15 Attack, +10% Crit',
    branch: 'offense',
    cost: 2,
    prerequisite: 'archer_deadly_aim',
    effect: { attack: 15, critChance: 10 },
    unlocked: false,
    row: 1,
    column: 0,
  },
  {
    id: 'archer_perfect_shot',
    name: 'Perfect Shot',
    description: '+25 Attack, +18% Crit',
    branch: 'offense',
    cost: 3,
    prerequisite: 'archer_headshot',
    effect: { attack: 25, critChance: 18 },
    unlocked: false,
    row: 2,
    column: 0,
  },
  
  // Mobility Branch
  {
    id: 'archer_quick_step',
    name: 'Quick Step',
    description: '+10 Speed, +5% Evasion',
    branch: 'defense',
    cost: 1,
    prerequisite: null,
    effect: { speed: 10, evasion: 5 },
    unlocked: false,
    row: 0,
    column: 1,
  },
  {
    id: 'archer_acrobat',
    name: 'Acrobat',
    description: '+15 Speed, +10% Evasion',
    branch: 'defense',
    cost: 2,
    prerequisite: 'archer_quick_step',
    effect: { speed: 15, evasion: 10 },
    unlocked: false,
    row: 1,
    column: 1,
  },
  {
    id: 'archer_shadow_walk',
    name: 'Shadow Walk',
    description: '+25 Speed, +15% Evasion',
    branch: 'defense',
    cost: 3,
    prerequisite: 'archer_acrobat',
    effect: { speed: 25, evasion: 15 },
    unlocked: false,
    row: 2,
    column: 1,
  },
  
  // Traps Branch
  {
    id: 'archer_snare',
    name: 'Snare',
    description: '+8 Defense, +10 Luck',
    branch: 'utility',
    cost: 1,
    prerequisite: null,
    effect: { defense: 8, luck: 10 },
    unlocked: false,
    row: 0,
    column: 2,
  },
  {
    id: 'archer_poison_trap',
    name: 'Poison Trap',
    description: '+12 Attack, +12 Defense',
    branch: 'utility',
    cost: 2,
    prerequisite: 'archer_snare',
    effect: { attack: 12, defense: 12 },
    unlocked: false,
    row: 1,
    column: 2,
  },
  {
    id: 'archer_death_trap',
    name: 'Death Trap',
    description: '+20 Attack, +15 Defense',
    branch: 'utility',
    cost: 3,
    prerequisite: 'archer_poison_trap',
    effect: { attack: 20, defense: 15 },
    unlocked: false,
    row: 2,
    column: 2,
  },
];

export const getSkillTreeForClass = (characterClass: CharacterClass): SkillTree => {
  switch (characterClass) {
    case 'fighter':
      return { class: 'fighter', nodes: FIGHTER_NODES };
    case 'mage':
      return { class: 'mage', nodes: MAGE_NODES };
    case 'archer':
      return { class: 'archer', nodes: ARCHER_NODES };
    default:
      return { class: 'fighter', nodes: FIGHTER_NODES };
  }
};
